### ISSUE TITLE
I tried to run this code on my own

### ISSUE THREAD

**Issue by vanmagnan** [allenjstewart/SU_Python_Group#1]
I tried to run this code on my own, and my console didnt seem to like line 57- it gave me the following error:
  File "C:/Users/vanma/Documents/Nonlinear_Research/AJNewton.py", line 57
    fnumpoint[k]=syp.sympify(f[k]).subs(varpoint)
                   ^
SyntaxError: invalid syntax

I believe that the carat is finding some issue with fnumpoint? I can't really tell why. Maybe the problem is strictly local.

**Comment by christinelindcole** [comment]
Same:

 File "Newtons.py", line 57
    fnumpoint[k]=syp.sympify(f[k]).subs(varpoint)
            ^
SyntaxError: invalid syntax

**Comment by allenjstewart** [comment]
I just pushed a new version. There was a missing parentheses in the git version I uploaded.
